import {
    Alignment,
    Autoformat,
    BlockQuote,
    Bold,
    Code,
    Italic,
    Strikethrough,
    Underline,
    CloudServices,
    List,
    ListProperties,
    Essentials,
    FindAndReplace,
    FontBackgroundColor,
    FontColor,
    FontFamily,
    FontSize,
    GeneralHtmlSupport,
    Heading,
    HorizontalLine,
    Image,
    ImageCaption,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    Indent,
    IndentBlock,
    Link,
    Paragraph,
    PasteFromOffice,
    RemoveFormat,
    Style,
    Table,
    TableCellProperties,
    TableColumnResize,
    TableProperties,
    TableToolbar,
    TextTransformation
} from 'ckeditor5';
// Import {SourceEditing} from 'ckeditor5';
import {Picker} from '~/CKEditor/Picker/Picker';
import {FormatPainter} from 'ckeditor5-premium-features';

export const plugins = [
    Alignment,
    Autoformat,
    BlockQuote,
    Bold,
    CloudServices,
    Code,
    List,
    ListProperties,
    Essentials,
    FindAndReplace,
    FontBackgroundColor,
    FontColor,
    FontFamily,
    FontSize,
    FormatPainter,
    GeneralHtmlSupport,
    Heading,
    HorizontalLine,
    Image,
    ImageCaption,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    Indent,
    IndentBlock,
    Italic,
    Link,
    Paragraph,
    PasteFromOffice,
    RemoveFormat,
    // Temporary removal, issues to be fixed in later versions
    // SourceEditing,
    Strikethrough,
    Style,
    Table,
    TableCellProperties,
    TableColumnResize,
    TableProperties,
    TableToolbar,
    TextTransformation,
    Underline,
    Picker
];
