import {registry} from '@jahia/ui-extender';
import {JahiaClassicEditor} from '~/CKEditor/JahiaClassicEditor';
import {JahiaBalloonEditor} from '~/CKEditor/JahiaBalloonEditor';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import CloudServices from '@ckeditor/ckeditor5-cloud-services/src/cloudservices';
import Code from '@ckeditor/ckeditor5-basic-styles/src/code';
import DocumentList from '@ckeditor/ckeditor5-list/src/documentlist';
import DocumentListProperties from '@ckeditor/ckeditor5-list/src/documentlistproperties';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import ExportPdf from '@ckeditor/ckeditor5-export-pdf/src/exportpdf';
import FindAndReplace from '@ckeditor/ckeditor5-find-and-replace/src/findandreplace';
import FontBackgroundColor from '@ckeditor/ckeditor5-font/src/fontbackgroundcolor';
import FontColor from '@ckeditor/ckeditor5-font/src/fontcolor';
import FontFamily from '@ckeditor/ckeditor5-font/src/fontfamily';
import FontSize from '@ckeditor/ckeditor5-font/src/fontsize';
import GeneralHtmlSupport from '@ckeditor/ckeditor5-html-support/src/generalhtmlsupport';
import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import HorizontalLine from '@ckeditor/ckeditor5-horizontal-line/src/horizontalline';
import HtmlEmbed from '@ckeditor/ckeditor5-html-embed/src/htmlembed';
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageResize from '@ckeditor/ckeditor5-image/src/imageresize';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import Indent from '@ckeditor/ckeditor5-indent/src/indent';
import IndentBlock from '@ckeditor/ckeditor5-indent/src/indentblock';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Link from '@ckeditor/ckeditor5-link/src/link';
import MediaEmbed from '@ckeditor/ckeditor5-media-embed/src/mediaembed';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';
import RemoveFormat from '@ckeditor/ckeditor5-remove-format/src/removeformat';
import SourceEditing from '@ckeditor/ckeditor5-source-editing/src/sourceediting';
import SpecialCharacters from '@ckeditor/ckeditor5-special-characters/src/specialcharacters';
import SpecialCharactersEssentials from '@ckeditor/ckeditor5-special-characters/src/specialcharactersessentials';
import Strikethrough from '@ckeditor/ckeditor5-basic-styles/src/strikethrough';
import Style from '@ckeditor/ckeditor5-style/src/style';
import Table from '@ckeditor/ckeditor5-table/src/table';
import TableCellProperties from '@ckeditor/ckeditor5-table/src/tablecellproperties';
import TableColumnResize from '@ckeditor/ckeditor5-table/src/tablecolumnresize';
import TableProperties from '@ckeditor/ckeditor5-table/src/tableproperties';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';
import TextTransformation from '@ckeditor/ckeditor5-typing/src/texttransformation';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline';
import {Picker} from '~/CKEditor/Picker/Picker';
import CKBox from '@ckeditor/ckeditor5-ckbox/src/ckbox';
import List from '@ckeditor/ckeditor5-list/src/list';
import PictureEditing from '@ckeditor/ckeditor5-image/src/pictureediting';

export const registerPlugins = () => {
    registry.addOrReplace('ckeditor-plugin', 'Alignment', {targets: ['classic'], plugin: Alignment});
    registry.addOrReplace('ckeditor-plugin', 'Autoformat', {targets: ['classic', 'balloon'], plugin: Autoformat});
    registry.addOrReplace('ckeditor-plugin', 'BlockQuote', {targets: ['classic', 'balloon'], plugin: BlockQuote});
    registry.addOrReplace('ckeditor-plugin', 'Bold', {targets: ['classic', 'balloon'], plugin: Bold});
    registry.addOrReplace('ckeditor-plugin', 'CKBox', {targets: ['balloon'], plugin: CKBox});
    registry.addOrReplace('ckeditor-plugin', 'CloudServices', {targets: ['classic', 'balloon'], plugin: CloudServices});
    registry.addOrReplace('ckeditor-plugin', 'Code', {targets: ['classic'], plugin: Code});
    registry.addOrReplace('ckeditor-plugin', 'DocumentList', {targets: ['classic'], plugin: DocumentList});
    registry.addOrReplace('ckeditor-plugin', 'DocumentListProperties', {
        targets: ['classic'],
        plugin: DocumentListProperties
    });
    registry.addOrReplace('ckeditor-plugin', 'Essentials', {targets: ['classic', 'balloon'], plugin: Essentials});
    registry.addOrReplace('ckeditor-plugin', 'ExportPdf', {targets: ['classic'], plugin: ExportPdf});
    registry.addOrReplace('ckeditor-plugin', 'FindAndReplace', {targets: ['classic'], plugin: FindAndReplace});
    registry.addOrReplace('ckeditor-plugin', 'FontBackgroundColor', {targets: ['classic'], plugin: FontBackgroundColor});
    registry.addOrReplace('ckeditor-plugin', 'FontColor', {targets: ['classic'], plugin: FontColor});
    registry.addOrReplace('ckeditor-plugin', 'FontFamily', {targets: ['classic'], plugin: FontFamily});
    registry.addOrReplace('ckeditor-plugin', 'FontSize', {targets: ['classic'], plugin: FontSize});
    registry.addOrReplace('ckeditor-plugin', 'GeneralHtmlSupport', {targets: ['classic', 'balloon'], plugin: GeneralHtmlSupport});
    registry.addOrReplace('ckeditor-plugin', 'Heading', {targets: ['classic', 'balloon'], plugin: Heading});
    registry.addOrReplace('ckeditor-plugin', 'HorizontalLine', {targets: ['classic'], plugin: HorizontalLine});
    registry.addOrReplace('ckeditor-plugin', 'HtmlEmbed', {targets: ['classic'], plugin: HtmlEmbed});
    registry.addOrReplace('ckeditor-plugin', 'Image', {targets: ['classic', 'balloon'], plugin: Image});
    registry.addOrReplace('ckeditor-plugin', 'ImageCaption', {targets: ['classic', 'balloon'], plugin: ImageCaption});
    registry.addOrReplace('ckeditor-plugin', 'ImageResize', {targets: ['classic'], plugin: ImageResize});
    registry.addOrReplace('ckeditor-plugin', 'ImageStyle', {targets: ['classic', 'balloon'], plugin: ImageStyle});
    registry.addOrReplace('ckeditor-plugin', 'ImageToolbar', {targets: ['classic', 'balloon'], plugin: ImageToolbar});
    registry.addOrReplace('ckeditor-plugin', 'ImageUpload', {targets: ['classic', 'balloon'], plugin: ImageUpload});
    registry.addOrReplace('ckeditor-plugin', 'Indent', {targets: ['classic', 'balloon'], plugin: Indent});
    registry.addOrReplace('ckeditor-plugin', 'IndentBlock', {targets: ['classic'], plugin: IndentBlock});
    registry.addOrReplace('ckeditor-plugin', 'Italic', {targets: ['classic', 'balloon'], plugin: Italic});
    registry.addOrReplace('ckeditor-plugin', 'Link', {targets: ['classic', 'balloon'], plugin: Link});
    registry.addOrReplace('ckeditor-plugin', 'List', {targets: ['balloon'], plugin: List});
    registry.addOrReplace('ckeditor-plugin', 'MediaEmbed', {targets: ['classic', 'balloon'], plugin: MediaEmbed});
    registry.addOrReplace('ckeditor-plugin', 'Paragraph', {targets: ['classic', 'balloon'], plugin: Paragraph});
    registry.addOrReplace('ckeditor-plugin', 'PasteFromOffice', {targets: ['classic', 'balloon'], plugin: PasteFromOffice});
    registry.addOrReplace('ckeditor-plugin', 'PictureEditing', {targets: ['balloon'], plugin: PictureEditing});
    registry.addOrReplace('ckeditor-plugin', 'RemoveFormat', {targets: ['classic'], plugin: RemoveFormat});
    registry.addOrReplace('ckeditor-plugin', 'SourceEditing', {targets: ['classic'], plugin: SourceEditing});
    registry.addOrReplace('ckeditor-plugin', 'SpecialCharacters', {targets: ['classic'], plugin: SpecialCharacters});
    registry.addOrReplace('ckeditor-plugin', 'SpecialCharactersEssentials', {
        targets: ['classic'],
        plugin: SpecialCharactersEssentials
    });
    registry.addOrReplace('ckeditor-plugin', 'Strikethrough', {targets: ['classic'], plugin: Strikethrough});
    registry.addOrReplace('ckeditor-plugin', 'Style', {targets: ['classic'], plugin: Style});
    registry.addOrReplace('ckeditor-plugin', 'Table', {targets: ['classic', 'balloon'], plugin: Table});
    registry.addOrReplace('ckeditor-plugin', 'TableCellProperties', {targets: ['classic'], plugin: TableCellProperties});
    registry.addOrReplace('ckeditor-plugin', 'TableColumnResize', {targets: ['classic'], plugin: TableColumnResize});
    registry.addOrReplace('ckeditor-plugin', 'TableProperties', {targets: ['classic'], plugin: TableProperties});
    registry.addOrReplace('ckeditor-plugin', 'TableToolbar', {targets: ['classic', 'balloon'], plugin: TableToolbar});
    registry.addOrReplace('ckeditor-plugin', 'TextTransformation', {targets: ['classic', 'balloon'], plugin: TextTransformation});
    registry.addOrReplace('ckeditor-plugin', 'Underline', {targets: ['classic'], plugin: Underline});
    registry.addOrReplace('ckeditor-plugin', 'Picker', {targets: ['classic'], plugin: Picker});

    JahiaClassicEditor.builtinPlugins = registry.find({type: 'ckeditor-plugin', target: 'classic'}).map(m => m.plugin);
    JahiaBalloonEditor.builtinPlugins = registry.find({type: 'ckeditor-plugin', target: 'balloon'}).map(m => m.plugin);
};
