name: Nightly Test run

on:
  workflow_dispatch:
  schedule:
    - cron:  '15 1 * * *'

jobs:
  integration-tests-standalone:
    name: Integration Tests (Standalone)
    secrets: inherit
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    with:
      module_id: richtext-ckeditor5
      testrail_project: CKEditor 5 Module
      jahia_image: ghcr.io/jahia/jahia-ee-dev:8-SNAPSHOT
      provisioning_manifest: provisioning-manifest-snapshot.yml
      artifact_prefix: richtext-ckeditor5-standalone-artifacts
      timeout_job: 45