# This workflow is triggered every time a change is pushed to any branches
# Github actions command reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: On merge to main

# The workflow could also be triggered on PRs
on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  update-signature:
    name: Update module signature
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jahia/jahia-modules-action/update-signature@v2
        with:
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}

  build:
    name: Build Module
    needs: update-signature
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jahia/jahia-docker-mvn-cache:11-jdk-noble-mvn-loaded
      credentials:
        username: ${{ secrets.GH_PACKAGES_USERNAME }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        shell: bash
        env:
          CKEDITOR_PRODUCTIVITY_LICENSE: ${{ secrets.CKEDITOR_PRODUCTIVITY_LICENSE }}
        run: |
          echo "CKEDITOR_PRODUCTIVITY_LICENSE=${CKEDITOR_PRODUCTIVITY_LICENSE}" > .env
      - uses: jahia/jahia-modules-action/build@v2
        with:
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}

  integration-tests-standalone:
    name: Integration Tests (Standalone)
    needs: build
    secrets: inherit
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    with:
      module_id: richtext-ckeditor5
      testrail_project: CKEditor 5 Module
      jahia_image: ghcr.io/jahia/jahia-ee-dev:8-SNAPSHOT
      should_skip_testrail: true
      provisioning_manifest: provisioning-manifest-build.yml
      artifact_prefix: richtext-ckeditor5-standalone-artifacts
      timeout_job: 45

  publish:
    name: Publish module
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jahia/jahia-docker-mvn-cache:11-jdk-noble-mvn-loaded
      credentials:
        username: ${{ secrets.GH_PACKAGES_USERNAME }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        shell: bash
        env:
          CKEDITOR_PRODUCTIVITY_LICENSE: ${{ secrets.CKEDITOR_PRODUCTIVITY_LICENSE }}
        run: |
          echo "CKEDITOR_PRODUCTIVITY_LICENSE=${CKEDITOR_PRODUCTIVITY_LICENSE}" > .env
      - uses: jahia/jahia-modules-action/publish@v2
        with:
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
